#!/usr/bin/env python3
"""Generate cases.h: table-driven regression data with expected results computed by Python.

Everything is stored as raw bit patterns (uint32/uint64) so the C side never has to
parse a floating-point literal and never computes its own expectations.
Semantics reproduced exactly: C truncating division, two's-complement wraparound,
IEEE-754 round-to-nearest-even for + - * / sqrt and conversions (incl. a correctly
single-rounded int64 -> float).
"""
import math
import random
import struct
import sys

R = random.Random(20261001)
M32 = (1 << 32) - 1
M64 = (1 << 64) - 1
QNAN64 = 0x7FF8000000000000
QNAN32 = 0x7FC00000


def s32(x):
    x &= M32
    return x - (1 << 32) if x >> 31 else x


def s64(x):
    x &= M64
    return x - (1 << 64) if x >> 63 else x


def cdiv(a, b):
    q = abs(a) // abs(b)
    return q if (a < 0) == (b < 0) else -q


def cmod(a, b):
    return a - cdiv(a, b) * b


def d2b(x):
    return struct.unpack('<Q', struct.pack('<d', x))[0]


def b2d(b):
    return struct.unpack('<d', struct.pack('<Q', b))[0]


def f2b(x):
    return struct.unpack('<I', struct.pack('<f', x))[0]


def b2f(b):
    return struct.unpack('<f', struct.pack('<I', b))[0]


def rd(x):
    """double -> canonical bits (NaN canonicalised)"""
    return QNAN64 if x != x else d2b(x)


def rf(x):
    """Python double -> float32 bits with IEEE RNE, overflow -> inf, NaN canonical"""
    if x != x:
        return QNAN32
    try:
        return f2b(x)
    except OverflowError:
        return 0xFF800000 if x < 0 else 0x7F800000


def int_to_f32(n):
    """Correctly rounded (single rounding) integer -> float32 bits."""
    if n == 0:
        return 0
    sign = 0x80000000 if n < 0 else 0
    n = abs(n)
    b = n.bit_length()
    if b > 24:
        shift = b - 24
        q = n >> shift
        rem = n & ((1 << shift) - 1)
        half = 1 << (shift - 1)
        if rem > half or (rem == half and (q & 1)):
            q += 1
        n = q << shift
    return sign | f2b(float(n))


def is_sub64(x):
    return x == x and not math.isinf(x) and x != 0.0 and abs(x) < 2.2250738585072014e-308


def is_sub32(x):
    return x == x and not math.isinf(x) and x != 0.0 and abs(x) < 1.1754943508222875e-38


def clz(v, bits):
    return bits - v.bit_length()


def ctz(v):
    return (v & -v).bit_length() - 1


def popc(v):
    return bin(v).count('1')


def bswap(v, nbytes):
    return int.from_bytes(v.to_bytes(nbytes, 'little'), 'big')


def hx32(v):
    return '0x%08XU' % (v & M32)


def hx64(v):
    return 'UINT64_C(0x%016X)' % (v & M64)


out = []
w = out.append

w('/* Generated by gen_cases.py -- do not edit. Expected values computed with Python. */')
w('#ifndef CASES_H')
w('#define CASES_H')
w('#include <stdint.h>')
w('')

# ----------------------------------------------------------------------------- int32
E32 = [0, 1, 2, 3, 7, 10, 0xFF, 0x100, 0xFFFF, 0x10000, 0x7FFFFFFF, 0x80000000, 0x80000001,
       0xFFFFFFFF, 0xFFFFFFFE, 0xDEADBEEF, 0x12345678, 1000000007, 0xFFFF0000, 0x00FF00FF]


def rnd32():
    nb = R.randint(1, 32)
    v = R.getrandbits(nb)
    if R.random() < 0.5:
        v = (-v) & M32
    return v


pairs = [(a, b) for a in E32 for b in E32] + [(rnd32(), rnd32()) for _ in range(300)]
w('struct i32c { uint32_t a, b, sdiv, smod, udiv, umod, mul, shl, ushr, sshr, clz, ctz, popc, bswap, f_s, f_u;')
w('               uint64_t d_s, d_u; uint8_t sh, has_div; };')
w('static const struct i32c I32[] = {')
for a, b in pairs:
    sa, sb = s32(a), s32(b)
    has_div = b != 0 and not (sa == -(1 << 31) and sb == -1)
    sh = R.randint(0, 31)
    f = dict(
        sdiv=cdiv(sa, sb) & M32 if has_div else 0,
        smod=cmod(sa, sb) & M32 if has_div else 0,
        udiv=(a // b) if b else 0,
        umod=(a % b) if b else 0,
        mul=(a * b) & M32,
        shl=(a << sh) & M32,
        ushr=a >> sh,
        sshr=(sa >> sh) & M32,
        clz=clz(a, 32) if a else 0,
        ctz=ctz(a) if a else 0,
        popc=popc(a),
        bswap=bswap(a, 4),
        f_s=int_to_f32(sa),
        f_u=int_to_f32(a),
    )
    w('  {%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%d,%d},' % (
        hx32(a), hx32(b), hx32(f['sdiv']), hx32(f['smod']), hx32(f['udiv']), hx32(f['umod']),
        hx32(f['mul']), hx32(f['shl']), hx32(f['ushr']), hx32(f['sshr']), hx32(f['clz']),
        hx32(f['ctz']), hx32(f['popc']), hx32(f['bswap']), hx32(f['f_s']), hx32(f['f_u']),
        hx64(d2b(float(sa))), hx64(d2b(float(a))), sh, 1 if has_div else 0))
w('};')
w('#define N_I32 (sizeof(I32)/sizeof(I32[0]))')
w('')

# ----------------------------------------------------------------------------- int64
E64 = [0, 1, 2, 3, 10, 0xFF, 0xFFFF, 0x7FFFFFFF, 0x80000000, 0xFFFFFFFF, 0x100000000, 0x100000001,
       0x7FFFFFFFFFFFFFFF, 0x8000000000000000, 0x8000000000000001, 0xFFFFFFFFFFFFFFFF,
       0xFFFFFFFFFFFFFFFE, 0xDEADBEEFCAFEBABE, 1000000000000000000, 0x0123456789ABCDEF,
       0x00000001FFFFFFFF, 0xFFFFFFFF00000000]


def rnd64():
    nb = R.randint(1, 64)
    v = R.getrandbits(nb)
    if R.random() < 0.5:
        v = (-v) & M64
    return v


pairs = [(a, b) for a in E64 for b in E64] + [(rnd64(), rnd64()) for _ in range(400)]
w('struct i64c { uint64_t a, b, sdiv, smod, udiv, umod, mul, shl, ushr, sshr, clz, ctz, popc, bswap, d_s, d_u;')
w('               uint32_t f_s, f_u; uint8_t sh, has_div; };')
w('static const struct i64c I64[] = {')
for a, b in pairs:
    sa, sb = s64(a), s64(b)
    has_div = b != 0 and not (sa == -(1 << 63) and sb == -1)
    sh = R.randint(0, 63)
    vals = [
        a, b,
        cdiv(sa, sb) & M64 if has_div else 0,
        cmod(sa, sb) & M64 if has_div else 0,
        (a // b) if b else 0,
        (a % b) if b else 0,
        (a * b) & M64,
        (a << sh) & M64,
        a >> sh,
        (sa >> sh) & M64,
        clz(a, 64) if a else 0,
        ctz(a) if a else 0,
        popc(a),
        bswap(a, 8),
        d2b(float(sa)),
        d2b(float(a)),
    ]
    w('  {%s,%s,%s,%d,%d},' % (','.join(hx64(v) for v in vals),
                             hx32(int_to_f32(sa)), hx32(int_to_f32(a)), sh, 1 if has_div else 0))
w('};')
w('#define N_I64 (sizeof(I64)/sizeof(I64[0]))')
w('')

# ----------------------------------------------------------------------------- double arithmetic
SPEC64 = [0.0, -0.0, 1.0, -1.0, 0.5, 3.0, 1.0 / 3.0, 1e308, 1e-308, 5e-324, 2.2250738585072014e-308,
          1.7976931348623157e308, math.inf, -math.inf, math.nan, 123456789.125, -2.5e-10]


def rnd_double():
    kind = R.random()
    if kind < 0.7:
        e = R.randint(-40, 40)
    elif kind < 0.92:
        e = R.randint(-1020, 1020)
    else:
        e = R.randint(-1074, -1000)
    ef = max(0, min(2046, 1023 + e))
    bits = (R.getrandbits(1) << 63) | (ef << 52) | R.getrandbits(52)
    return b2d(bits)


def cmpmask(a, b):
    return ((a < b) << 0) | ((a <= b) << 1) | ((a > b) << 2) | ((a >= b) << 3) | ((a == b) << 4) | ((a != b) << 5)


def pydiv(a, b):
    if b == 0.0:
        if a == 0.0 or a != a:
            return math.nan
        return math.copysign(math.inf, a) * math.copysign(1.0, b)
    return a / b


pairs = [(a, b) for a in SPEC64 for b in SPEC64] + [(rnd_double(), rnd_double()) for _ in range(300)]
w('struct dc { uint64_t a, b, add, sub, mul, div; uint8_t dn, cmp; };')
w('static const struct dc D64[] = {')
for a, b in pairs:
    r_add, r_sub, r_mul, r_div = a + b, a - b, a * b, pydiv(a, b)
    dn = 1 if any(is_sub64(x) for x in (a, b, r_add, r_sub, r_mul, r_div)) else 0
    w('  {%s,%s,%s,%s,%s,%s,%d,%d},' % (hx64(rd(a)), hx64(rd(b)), hx64(rd(r_add)), hx64(rd(r_sub)),
                                         hx64(rd(r_mul)), hx64(rd(r_div)), dn, cmpmask(a, b)))
w('};')
w('#define N_D64 (sizeof(D64)/sizeof(D64[0]))')
w('')

# ----------------------------------------------------------------------------- float arithmetic
FLT_MAX = 3.4028234663852886e38
SPEC32 = [0.0, -0.0, 1.0, -1.0, 0.5, 3.0, b2f(f2b(1.0 / 3.0)), FLT_MAX, 1.1754943508222875e-38,
          1.401298464324817e-45, math.inf, -math.inf, math.nan, 16777216.0, 123456.75, -2.5e-10]


def rnd_float():
    kind = R.random()
    if kind < 0.8:
        e = R.randint(-20, 20)
    elif kind < 0.95:
        e = R.randint(-120, 120)
    else:
        e = R.randint(-126, -118)
    ef = max(0, min(254, 127 + e))
    bits = (R.getrandbits(1) << 31) | (ef << 23) | R.getrandbits(23)
    return b2f(bits)


pairs = [(a, b) for a in SPEC32 for b in SPEC32] + [(rnd_float(), rnd_float()) for _ in range(300)]
w('struct fc { uint32_t a, b, add, sub, mul, div; uint64_t ad; uint8_t dn, cmp; };')
w('static const struct fc F32[] = {')
for a, b in pairs:
    a, b = b2f(rf(a)), b2f(rf(b))
    r_add, r_sub, r_mul, r_div = a + b, a - b, a * b, pydiv(a, b)
    bits = [rf(r_add), rf(r_sub), rf(r_mul), rf(r_div)]
    dn = 1 if any(is_sub32(x) for x in (a, b)) or any(is_sub32(b2f(x)) for x in bits) else 0
    w('  {%s,%s,%s,%s,%s,%s,%s,%d,%d},' % (hx32(rf(a)), hx32(rf(b)), hx32(bits[0]), hx32(bits[1]), hx32(bits[2]),
                                           hx32(bits[3]), hx64(rd(float(a))), dn, cmpmask(a, b)))
w('};')
w('#define N_F32 (sizeof(F32)/sizeof(F32[0]))')
w('')

# ----------------------------------------------------------------------------- sqrt
w('struct sqc { uint64_t a, r; uint32_t fa, fr; uint8_t dn; };')
w('static const struct sqc SQ[] = {')
vals = [0.0, -0.0, 1.0, 2.0, 4.0, 0.25, 3.0, 1e-300, 1e300, math.inf, 5e-324, 2.2250738585072014e-308, 123456789.0,
        0.1, 1e10, 7.0, 1e-10, 65536.0, 1.5, 9.999999e22]
vals += [abs(rnd_double()) for _ in range(60)]
for x in vals:
    if x != x:
        continue
    xf = b2f(rf(x)) if x < 3e38 else 3.0
    w('  {%s,%s,%s,%s,%d},' % (hx64(rd(x)), hx64(rd(math.sqrt(x))), hx32(rf(xf)), hx32(rf(math.sqrt(xf))),
                              1 if is_sub64(x) or is_sub64(math.sqrt(x)) or is_sub32(xf) else 0))
w('};')
w('#define N_SQ (sizeof(SQ)/sizeof(SQ[0]))')
w('')

# ----------------------------------------------------------------------------- double/float -> integer (in-range only)
w('struct d2ic { uint64_t d; uint32_t i32, u32; uint64_t i64, u64; uint8_t ok; };')
w('static const struct d2ic D2I[] = {')
rows = []
for _ in range(220):
    cls = R.randint(0, 3)
    if cls == 0:
        v = R.uniform(-2147483648.0, 2147483647.0)
    elif cls == 1:
        v = R.uniform(0.0, 4294967295.0)
    elif cls == 2:
        v = R.uniform(-9.2e18, 9.2e18)
    else:
        v = R.uniform(0.0, 1.8e19)
    if R.random() < 0.3:
        v = math.floor(v) + R.choice([0.0, 0.5, 0.9999999999, -0.5, 0.25])
    rows.append(v)
rows += [0.5, -0.5, 0.9999999999999999, -0.9999999999999999, 2147483647.5, -2147483648.5, 4294967295.5,
         4294967296.0, 9223372036854774784.0, -9223372036854775808.0, 18446744073709549568.0, 1.0, -1.0, 0.0, -0.0]
for v in rows:
    t = int(v)
    ok = (1 if -(1 << 31) <= t <= (1 << 31) - 1 else 0) | (2 if 0 <= t <= M32 else 0) | \
         (4 if -(1 << 63) <= t <= (1 << 63) - 1 else 0) | (8 if 0 <= t <= M64 else 0)
    w('  {%s,%s,%s,%s,%s,%d},' % (hx64(d2b(v)), hx32(t & M32), hx32(t & M32), hx64(t & M64), hx64(t & M64), ok))
w('};')
w('#define N_D2I (sizeof(D2I)/sizeof(D2I[0]))')
w('')

w('struct f2ic { uint32_t f, i32, u32; uint64_t i64, u64; uint8_t ok; };')
w('static const struct f2ic F2I[] = {')
rows = []
for _ in range(160):
    cls = R.randint(0, 2)
    v = b2f(rf(R.uniform(-2.0e9, 2.0e9) if cls == 0 else R.uniform(0.0, 4.2e9) if cls == 1 else R.uniform(-9.0e18, 9.0e18)))
    rows.append(v)
rows += [0.5, -0.5, 0.99999994, -0.99999994, 16777216.0, -16777216.0, 2147483520.0, 4294967040.0, 1.0, -1.0, 0.0]
for v in rows:
    v = b2f(rf(v))
    t = int(v)
    ok = (1 if -(1 << 31) <= t <= (1 << 31) - 1 else 0) | (2 if 0 <= t <= M32 else 0) | \
         (4 if -(1 << 63) <= t <= (1 << 63) - 1 else 0) | (8 if 0 <= t <= M64 else 0)
    w('  {%s,%s,%s,%s,%s,%d},' % (hx32(rf(v)), hx32(t & M32), hx32(t & M32), hx64(t & M64), hx64(t & M64), ok))
w('};')
w('#define N_F2I (sizeof(F2I)/sizeof(F2I[0]))')
w('')

# ----------------------------------------------------------------------------- double -> float rounding (ties, subnormals, overflow)
w('struct d2fc { uint64_t d; uint32_t f; };')
w('static const struct d2fc D2F[] = {')


def next32(f):
    b = f2b(f)
    return b2f(b + 1)


rows = []
for _ in range(80):
    f = rnd_float()
    if f != f or math.isinf(f) or abs(f) > 3.0e38:
        continue
    g = next32(abs(f))
    mid = (abs(f) + g) / 2.0          # exact tie in double
    sgn = math.copysign(1.0, f)
    ulp = math.ldexp(1.0, math.frexp(mid)[1] - 53)      # one double ulp at mid
    rows += [sgn * mid, sgn * (mid + ulp), sgn * (mid - ulp)]
rows += [rnd_double() for _ in range(40)]
rows += [1.0 + 2.0 ** -24, 1.0 + 3.0 * 2.0 ** -24, 3.4028235677973366e38, 3.4028236e38, -3.4028236e38,
         1e-46, 7e-46, 1.4e-45, 2.8e-45, 1e300, -1e300, 0.1, 1.0 / 3.0, 16777217.0, 16777219.0]
for v in rows:
    if v != v:
        continue
    w('  {%s,%s},' % (hx64(d2b(v)), hx32(rf(v))))
w('};')
w('#define N_D2F (sizeof(D2F)/sizeof(D2F[0]))')
w('')
w('#endif /* CASES_H */')

open(sys.argv[1] if len(sys.argv) > 1 else 'cases.h', 'w').write('\n'.join(out) + '\n')
print('cases.h written: i32=%d i64=%d' % (len(E32) ** 2 + 300, len(E64) ** 2 + 400))
