/* rotest.c -- RISC OS GCC regression checks.
 *
 * Self-checking: prints one line per group, FAIL lines for anything wrong, and a final
 * "SUMMARY ... PASS|FAIL" line.  Exit status 0 = PASS.  "INFO" lines are properties of the
 * runtime / OS (denormal handling, unwinder, ...) that are reported but do not fail the run.
 *
 * Expected values come from cases.h (generated by gen_cases.py with Python), so this program
 * never computes its own expectations for the table-driven groups.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdarg.h>
#include <setjmp.h>
#include <math.h>
#include <stdatomic.h>
#ifndef NO_UNWIND
#include <unwind.h>
#endif
#ifdef WITH_DLOPEN
#include <dlfcn.h>
#endif
#include "cases.h"
#include "callee.h"
#include "picdata.h"

#ifndef ROTEST_CFG
#define ROTEST_CFG "unknown"
#endif

int pd_ext = 41;                       /* used by pd_read_ext() in picdata.c / libfoo */

/* ------------------------------------------------------------------ framework */
static int g_checks, g_fail, g_info, g_info_fail, g_gf, g_ip;
static const char *g_grp = "?";
#define LLU(x) ((unsigned long long)(x))

static void failv(int line, const char *fmt, ...)
{
    va_list ap;
    g_fail++;
    if (g_gf++ < 6) {
        printf("FAIL %s:%d ", g_grp, line);
        va_start(ap, fmt);
        vprintf(fmt, ap);
        va_end(ap);
        printf("\n");
    } else if (g_gf == 7) {
        printf("  ... more failures in this group suppressed\n");
    }
}

#define CHECKV(cond, ...) do { g_checks++; if (!(cond)) failv(__LINE__, __VA_ARGS__); } while (0)
#define CHECK(cond) CHECKV(cond, "%s", #cond)
#define INFOV(cond, ...) do { g_info++; if (!(cond)) { g_info_fail++; \
        if (g_ip++ < 8) { printf("INFO %s:%d ", g_grp, __LINE__); printf(__VA_ARGS__); printf("\n"); } } } while (0)

static uint64_t bits_d(double d) { uint64_t u; memcpy(&u, &d, 8); return u; }
static uint32_t bits_f(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }
static double d_from(uint64_t u) { double d; memcpy(&d, &u, 8); return d; }
static float f_from(uint32_t u) { float f; memcpy(&f, &u, 4); return f; }
static int nan64(uint64_t b) { return (b & UINT64_C(0x7FF0000000000000)) == UINT64_C(0x7FF0000000000000) && (b & UINT64_C(0x000FFFFFFFFFFFFF)); }
static int nan32(uint32_t b) { return (b & 0x7F800000u) == 0x7F800000u && (b & 0x007FFFFFu); }
static int m64(double r, uint64_t e) { return nan64(e) ? __builtin_isnan(r) : bits_d(r) == e; }
static int m32(float r, uint32_t e) { return nan32(e) ? __builtin_isnan(r) : bits_f(r) == e; }

static void *__attribute__((noinline, noipa)) opq_ptr(void *p) { return p; }
static double __attribute__((noinline, noipa)) opq_d(double x) { return x; }

/* ------------------------------------------------------------------ integers */
static void t_int32(void)
{
    for (unsigned i = 0; i < N_I32; i++) {
        const struct i32c *c = &I32[i];
        volatile uint32_t ua = c->a, ub = c->b;
        volatile int32_t sa = (int32_t)c->a, sb = (int32_t)c->b;
        volatile unsigned sh = c->sh;
        CHECKV((uint32_t)(ua * ub) == c->mul, "#%u mul %08x*%08x", i, (unsigned)ua, (unsigned)ub);
        if (c->has_div) {
            CHECKV((uint32_t)(sa / sb) == c->sdiv, "#%u sdiv %d/%d", i, (int)sa, (int)sb);
            CHECKV((uint32_t)(sa % sb) == c->smod, "#%u smod %d%%%d", i, (int)sa, (int)sb);
        }
        if (ub) {
            CHECKV(ua / ub == c->udiv, "#%u udiv %u/%u", i, (unsigned)ua, (unsigned)ub);
            CHECKV(ua % ub == c->umod, "#%u umod %u%%%u", i, (unsigned)ua, (unsigned)ub);
        }
        CHECKV((uint32_t)(ua << sh) == c->shl, "#%u shl %08x<<%u", i, (unsigned)ua, sh);
        CHECKV((ua >> sh) == c->ushr, "#%u ushr %08x>>%u", i, (unsigned)ua, sh);
        CHECKV((uint32_t)(sa >> sh) == c->sshr, "#%u sshr %d>>%u", i, (int)sa, sh);
        if (ua) {
            CHECKV((uint32_t)__builtin_clz(ua) == c->clz, "#%u clz %08x", i, (unsigned)ua);
            CHECKV((uint32_t)__builtin_ctz(ua) == c->ctz, "#%u ctz %08x", i, (unsigned)ua);
        }
        CHECKV((uint32_t)__builtin_popcount(ua) == c->popc, "#%u popcount %08x", i, (unsigned)ua);
        CHECKV(__builtin_bswap32(ua) == c->bswap, "#%u bswap32 %08x", i, (unsigned)ua);
        CHECKV(bits_d((double)sa) == c->d_s, "#%u (double)int %d", i, (int)sa);
        CHECKV(bits_d((double)ua) == c->d_u, "#%u (double)uint %u", i, (unsigned)ua);
        CHECKV(bits_f((float)sa) == c->f_s, "#%u (float)int %d", i, (int)sa);
        CHECKV(bits_f((float)ua) == c->f_u, "#%u (float)uint %u", i, (unsigned)ua);
    }
}

static void t_int64(void)
{
    for (unsigned i = 0; i < N_I64; i++) {
        const struct i64c *c = &I64[i];
        volatile uint64_t ua = c->a, ub = c->b;
        volatile int64_t sa = (int64_t)c->a, sb = (int64_t)c->b;
        volatile unsigned sh = c->sh;
        CHECKV((uint64_t)(ua * ub) == c->mul, "#%u mul %016llx*%016llx", i, LLU(ua), LLU(ub));
        if (c->has_div) {
            CHECKV((uint64_t)(sa / sb) == c->sdiv, "#%u sdiv %lld/%lld", i, (long long)sa, (long long)sb);
            CHECKV((uint64_t)(sa % sb) == c->smod, "#%u smod %lld%%%lld", i, (long long)sa, (long long)sb);
        }
        if (ub) {
            CHECKV(ua / ub == c->udiv, "#%u udiv %llu/%llu", i, LLU(ua), LLU(ub));
            CHECKV(ua % ub == c->umod, "#%u umod %llu%%%llu", i, LLU(ua), LLU(ub));
        }
        CHECKV((uint64_t)(ua << sh) == c->shl, "#%u shl64 %016llx<<%u", i, LLU(ua), sh);
        CHECKV((ua >> sh) == c->ushr, "#%u ushr64 %016llx>>%u", i, LLU(ua), sh);
        CHECKV((uint64_t)(sa >> sh) == c->sshr, "#%u sshr64 %lld>>%u", i, (long long)sa, sh);
        if (ua) {
            CHECKV((uint64_t)__builtin_clzll(ua) == c->clz, "#%u clzll %016llx", i, LLU(ua));
            CHECKV((uint64_t)__builtin_ctzll(ua) == c->ctz, "#%u ctzll %016llx", i, LLU(ua));
        }
        CHECKV((uint64_t)__builtin_popcountll(ua) == c->popc, "#%u popcountll %016llx", i, LLU(ua));
        CHECKV(__builtin_bswap64(ua) == c->bswap, "#%u bswap64 %016llx", i, LLU(ua));
        CHECKV(bits_d((double)sa) == c->d_s, "#%u (double)int64 %lld", i, (long long)sa);
        CHECKV(bits_d((double)ua) == c->d_u, "#%u (double)uint64 %llu", i, LLU(ua));
        CHECKV(bits_f((float)sa) == c->f_s, "#%u (float)int64 %lld", i, (long long)sa);
        CHECKV(bits_f((float)ua) == c->f_u, "#%u (float)uint64 %llu", i, LLU(ua));
    }
}

/* ------------------------------------------------------------------ floating point */
static void t_f64(void)
{
    for (unsigned i = 0; i < N_D64; i++) {
        const struct dc *c = &D64[i];
        volatile double a = d_from(c->a), b = d_from(c->b);
        double r_add = a + b, r_sub = a - b, r_mul = a * b, r_div = a / b;
        if (c->dn) {
            INFOV(m64(r_add, c->add) && m64(r_sub, c->sub) && m64(r_mul, c->mul) && m64(r_div, c->div),
                  "denormal row #%u differs (flush-to-zero in use?)", i);
        } else {
            CHECKV(m64(r_add, c->add), "#%u %016llx + %016llx = %016llx want %016llx", i, LLU(c->a), LLU(c->b), LLU(bits_d(r_add)), LLU(c->add));
            CHECKV(m64(r_sub, c->sub), "#%u %016llx - %016llx = %016llx want %016llx", i, LLU(c->a), LLU(c->b), LLU(bits_d(r_sub)), LLU(c->sub));
            CHECKV(m64(r_mul, c->mul), "#%u %016llx * %016llx = %016llx want %016llx", i, LLU(c->a), LLU(c->b), LLU(bits_d(r_mul)), LLU(c->mul));
            CHECKV(m64(r_div, c->div), "#%u %016llx / %016llx = %016llx want %016llx", i, LLU(c->a), LLU(c->b), LLU(bits_d(r_div)), LLU(c->div));
        }
        unsigned m = (a < b) | ((a <= b) << 1) | ((a > b) << 2) | ((a >= b) << 3) | ((a == b) << 4) | ((a != b) << 5);
        CHECKV(m == c->cmp, "#%u compare mask %02x want %02x (%016llx ? %016llx)", i, m, (unsigned)c->cmp, LLU(c->a), LLU(c->b));
    }
}

static void t_f32(void)
{
    for (unsigned i = 0; i < N_F32; i++) {
        const struct fc *c = &F32[i];
        volatile float a = f_from(c->a), b = f_from(c->b);
        float r_add = a + b, r_sub = a - b, r_mul = a * b, r_div = a / b;
        if (c->dn) {
            INFOV(m32(r_add, c->add) && m32(r_sub, c->sub) && m32(r_mul, c->mul) && m32(r_div, c->div),
                  "float denormal row #%u differs (flush-to-zero in use?)", i);
        } else {
            CHECKV(m32(r_add, c->add), "#%u %08x + %08x = %08x want %08x", i, (unsigned)c->a, (unsigned)c->b, (unsigned)bits_f(r_add), (unsigned)c->add);
            CHECKV(m32(r_sub, c->sub), "#%u %08x - %08x = %08x want %08x", i, (unsigned)c->a, (unsigned)c->b, (unsigned)bits_f(r_sub), (unsigned)c->sub);
            CHECKV(m32(r_mul, c->mul), "#%u %08x * %08x = %08x want %08x", i, (unsigned)c->a, (unsigned)c->b, (unsigned)bits_f(r_mul), (unsigned)c->mul);
            CHECKV(m32(r_div, c->div), "#%u %08x / %08x = %08x want %08x", i, (unsigned)c->a, (unsigned)c->b, (unsigned)bits_f(r_div), (unsigned)c->div);
        }
        unsigned m = (a < b) | ((a <= b) << 1) | ((a > b) << 2) | ((a >= b) << 3) | ((a == b) << 4) | ((a != b) << 5);
        CHECKV(m == c->cmp, "#%u float compare mask %02x want %02x", i, m, (unsigned)c->cmp);
        volatile double ad = (double)a;
        CHECKV(m64(ad, c->ad), "#%u (double)float %08x", i, (unsigned)c->a);
    }
}

static void t_conv(void)
{
    for (unsigned i = 0; i < N_D2I; i++) {
        const struct d2ic *c = &D2I[i];
        volatile double d = d_from(c->d);
        if (c->ok & 1) CHECKV((uint32_t)(int32_t)d == c->i32, "#%u (int)%.17g", i, (double)d);
        if (c->ok & 2) CHECKV((uint32_t)d == c->u32, "#%u (unsigned)%.17g", i, (double)d);
        if (c->ok & 4) CHECKV((uint64_t)(int64_t)d == c->i64, "#%u (int64)%.17g", i, (double)d);
        if (c->ok & 8) CHECKV((uint64_t)d == c->u64, "#%u (uint64)%.17g", i, (double)d);
    }
    for (unsigned i = 0; i < N_F2I; i++) {
        const struct f2ic *c = &F2I[i];
        volatile float f = f_from(c->f);
        if (c->ok & 1) CHECKV((uint32_t)(int32_t)f == c->i32, "#%u (int)float %08x", i, (unsigned)c->f);
        if (c->ok & 2) CHECKV((uint32_t)f == c->u32, "#%u (unsigned)float %08x", i, (unsigned)c->f);
        if (c->ok & 4) CHECKV((uint64_t)(int64_t)f == c->i64, "#%u (int64)float %08x", i, (unsigned)c->f);
        if (c->ok & 8) CHECKV((uint64_t)f == c->u64, "#%u (uint64)float %08x", i, (unsigned)c->f);
    }
    for (unsigned i = 0; i < N_D2F; i++) {
        const struct d2fc *c = &D2F[i];
        volatile double d = d_from(c->d);
        CHECKV(bits_f((float)d) == c->f, "#%u (float)%016llx = %08x want %08x", i, LLU(c->d), (unsigned)bits_f((float)d), (unsigned)c->f);
    }
    for (unsigned i = 0; i < N_SQ; i++) {
        const struct sqc *c = &SQ[i];
        volatile double x = d_from(c->a);
        volatile float xf = f_from(c->fa);
        if (c->dn) {
            INFOV(bits_d(__builtin_sqrt(x)) == c->r && bits_f(__builtin_sqrtf(xf)) == c->fr, "sqrt denormal row #%u differs", i);
        } else {
            CHECKV(bits_d(__builtin_sqrt(x)) == c->r, "#%u sqrt(%016llx)", i, LLU(c->a));
            CHECKV(bits_f(__builtin_sqrtf(xf)) == c->fr, "#%u sqrtf(%08x)", i, (unsigned)c->fa);
        }
    }
}

static void t_fpmisc(void)
{
    volatile double n = __builtin_nan(""), one = 1.0, zero = 0.0, nzero = -0.0, inf = __builtin_inf(), big = 1e308;
    CHECK(!(n == n)); CHECK(n != n); CHECK(!(n < one)); CHECK(!(n > one)); CHECK(!(n <= one)); CHECK(!(n >= one));
    CHECK(zero == nzero); CHECK(!(nzero < zero)); CHECK(inf > big); CHECK(-inf < -big);
    CHECK(__builtin_isunordered(n, one)); CHECK(!__builtin_isunordered(inf, one));
    CHECK(__builtin_signbit(nzero) != 0); CHECK(__builtin_signbit(zero) == 0);
    CHECK(one / nzero == -inf); CHECK(one / zero == inf);
    CHECK(__builtin_isnan(zero / zero)); CHECK(__builtin_isnan(inf - inf)); CHECK(__builtin_isnan(zero * inf));
    volatile double x = -1.5, h = 2.5, h2 = 3.5, ax = -2.5;
    CHECK(__builtin_fabs(ax) == 2.5);
    CHECK(__builtin_floor(x) == -2.0); CHECK(__builtin_ceil(x) == -1.0); CHECK(__builtin_trunc(x) == -1.0);
    CHECK(__builtin_round(h) == 3.0); CHECK(__builtin_rint(h) == 2.0); CHECK(__builtin_rint(h2) == 4.0);
    CHECK(__builtin_copysign(3.0, nzero) == -3.0);
    volatile float fx = -1.5f, fh = 2.5f;
    CHECK(__builtin_floorf(fx) == -2.0f); CHECK(__builtin_ceilf(fx) == -1.0f); CHECK(__builtin_truncf(fx) == -1.0f);
    CHECK(__builtin_roundf(fh) == 3.0f);
    volatile float tenth = 0.1f;
    CHECK((double)tenth == 0.10000000149011612);
    /* default rounding mode is nearest-even and there is no extended precision */
    volatile double u = 1.0, tiny = 1.1102230246251565e-16 /* 2^-53 */, ulp = 2.220446049250313e-16 /* 2^-52 */;
    CHECK(u + tiny == 1.0); CHECK(u + ulp != 1.0); CHECK(u + (ulp + tiny) == 1.0000000000000004);
    volatile double third = opq_d(1.0) / opq_d(3.0);
    CHECK(bits_d(third) == UINT64_C(0x3FD5555555555555));
}

static void t_complex(void)
{
    volatile double _Complex a = 1.0 + 2.0i, b = 3.0 - 4.0i;
    double _Complex m = a * b;
    CHECKV(__real__ m == 11.0 && __imag__ m == 2.0, "cmul got %g%+gi", __real__ m, __imag__ m);
    double _Complex q = a / b;
    CHECKV(__builtin_fabs(__real__ q + 0.2) < 1e-14 && __builtin_fabs(__imag__ q - 0.4) < 1e-14, "cdiv got %g%+gi", __real__ q, __imag__ q);
    volatile float _Complex fa = 1.5f + 0.5fi, fb = 2.0f - 1.0fi;
    float _Complex fm = fa * fb;
    CHECKV(__real__ fm == 3.5f && __imag__ fm == -0.5f, "fcmul got %g%+gi", (double)__real__ fm, (double)__imag__ fm);
    float _Complex fq = fa / fb;                       /* (1.5+0.5i)/(2-1i) = (3-0.5 + (1.5+1)i)/5 = 0.5+0.5i */
    CHECKV(__builtin_fabsf(__real__ fq - 0.5f) < 1e-6f && __builtin_fabsf(__imag__ fq - 0.5f) < 1e-6f, "fcdiv got %g%+gi", (double)__real__ fq, (double)__imag__ fq);
    double _Complex cj = ~a;
    CHECK(__real__ cj == 1.0 && __imag__ cj == -2.0);
}

/* ------------------------------------------------------------------ calling convention */
static int cb_add(int a, int b) { return a + b; }
static int cb_sub(int a, int b) { return a - b; }
static int cb_mix(int a, int b) { return a * 3 + b; }

static void t_abi(void)
{
    {
        volatile int a = 3; volatile double b = 2.5; volatile float c = 1.25f; volatile long long d = 40000000000LL;
        volatile double e = -6.5; volatile signed char f = -7; volatile short g = 300; volatile double h = 0.125;
        double r = abi_mix1(a, b, c, d, e, f, g, h);
        double want = 3 + 2.5 + 1.25 + 40000000000.0 - 6.5 - 7 + 300 + 0.125;
        CHECKV(r == want, "mix1 got %.17g want %.17g", r, want);
    }
    {
        volatile double d0 = 1, d1 = 2, d2 = 3, d3 = 4, d4 = 5, d5 = 6, d6 = 7, d7 = 8, d8 = 9, d10 = 0.5;
        volatile float f9 = 1.5f;
        volatile int i0 = 1, i1 = 2, i2 = 3, i3 = 4, i4 = 5;
        double r = abi_many(d0, d1, d2, d3, d4, d5, d6, d7, d8, f9, i0, i1, i2, i3, i4, d10);
        double want = 1 + 2 * 2 + 3 * 3 + 4 * 4 + 5 * 5 + 6 * 6 + 7 * 7 + 8 * 8 + 9 * 9 + 1.5 * 10 + 1 * 11 + 2 * 12 + 3 * 13 + 4 * 14 + 5 * 15 + 0.5 * 16;
        CHECKV(r == want, "many got %.17g want %.17g", r, want);
    }
    {
        D2 a = { 1.5, 2.5 }, b = { 4.0, -8.0 };
        D2 r = abi_d2(a, b);
        CHECKV(r.x == a.x + b.y && r.y == a.y * b.x, "d2 got %g,%g", r.x, r.y);
    }
    {
        F4 a = { 1.0f, 2.0f, 3.0f, 4.0f };
        F4 r = abi_f4(a, 0.5f);
        CHECKV(r.a == 1.5f && r.b == 3.0f && r.c == 4.5f && r.d == 6.0f, "f4 got %g %g %g %g", (double)r.a, (double)r.b, (double)r.c, (double)r.d);
    }
    {
        F5 a = { 1, 2, 3, 4, 5 }, b = { 10, 20, 30, 40, 50 };
        F5 r = abi_f5(a, b);
        CHECKV(r.a == 11 && r.b == 22 && r.c == 33 && r.d == 44 && r.e == 55, "f5 got %g %g %g %g %g", (double)r.a, (double)r.b, (double)r.c, (double)r.d, (double)r.e);
    }
    {
        ID a = { 5, 1.25 };
        ID r = abi_id(a, 4);
        CHECKV(r.i == 9 && r.d == 5.0, "id got %d,%g", r.i, r.d);
    }
    {
        C7 a = { { 1, 2, 3, 4, 5, 6, 7 } };
        C7 r = abi_c7(a);
        int ok = 1;
        for (int i = 0; i < 7; i++) ok &= (r.c[i] == 7 - i);
        CHECK(ok);
    }
    {
        LL3 a = { 1000000000000LL, 2000000000000LL, 0xF0 }, b = { 3LL, 4000000000000LL, 0x3C };
        LL3 r = abi_ll3(a, b);
        CHECKV(r.a == 5000000000000LL && r.b == 1999999999997LL && r.c == 0xCC, "ll3 got %lld %lld %d", (long long)r.a, (long long)r.b, r.c);
    }
    {
        D3 a = { { 1.5, 2.5, 3.5 } };
        D3 r = abi_d3(a, 2.0);
        CHECKV(r.a[0] == 3.0 && r.a[1] == 4.5 && r.a[2] == 1.5, "d3 got %g %g %g", r.a[0], r.a[1], r.a[2]);
    }
    {
        BIG a, r;
        for (int i = 0; i < 16; i++) a.v[i] = i * i;
        r = abi_big(a, 3);
        int ok = 1;
        for (int i = 0; i < 16; i++) ok &= (r.v[i] == i * i + 3 * i);
        CHECK(ok);
    }
    {
        SMALL a = { 10, -300, 7 }, b = { 5, 200, -3 };
        SMALL r = abi_small(a, b);
        CHECKV(r.a == 15 && r.b == -500 && r.c == -21, "small got %d %d %d", r.a, r.b, r.c);
    }
    {
        volatile signed char a1 = -5, a2 = 127, a3 = -128;
        volatile unsigned char b1 = 250, b2 = 255, b3 = 0;
        volatile short c1 = -300, c2 = 32767, c3 = -32768;
        volatile unsigned short d1 = 60000, d2 = 65535, d3 = 0;
        volatile _Bool e1 = 1, e3 = 1;
        CHECK(abi_narrow(a1, b1, c1, d1, e1) == -5 * 1000000 + 250 * 10000 + -300 * 100 + 60000 + 7);
        CHECK(abi_narrow(a2, b2, c2, d2, 0) == 127 * 1000000 + 255 * 10000 + 32767 * 100 + 65535);
        CHECK(abi_narrow(a3, b3, c3, d3, e3) == -128 * 1000000 + 0 + -32768 * 100 + 0 + 7);
    }
    {
        volatile long long a = 0x100000001LL, b = -5LL;
        CHECK(abi_ll(a, b) == 0x100000001LL * 3 + 5);
        volatile unsigned long long ua = 0x123456789ULL, ub = 0xFEDCBA987ULL;
        CHECK(abi_skew(7, ua, ub) == 0x123456789ULL * 5 + 0xFEDCBA987ULL + 7);
    }
    {
        volatile float a = 1.5f, b = 2.0f;
        CHECK(abi_fret(a, b) == 3.5f);
    }
    {
        volatile double _Complex a = 1.0 + 2.0i, b = 3.0 - 4.0i;
        double _Complex r = abi_cplx(a, b);
        CHECKV(__real__ r == 12.0 && __imag__ r == 2.0, "cplx got %g%+gi", __real__ r, __imag__ r);
    }
    {
        CHECK(abi_cb(cb_sub, 10, 3) == (10 - 3) + (3 - 10) * 2);
        CHECK(abi_cb(cb_mix, 2, 5) == (2 * 3 + 5) + (5 * 3 + 2) * 2);
        CHECK(abi_cb(cb_add, 100, 1) == 101 + 101 * 2);
        int i = 0; double d = 0; long long ll = 0; float f = 0;
        abi_out(&i, &d, &ll, &f);
        CHECKV(i == 123456 && d == 2.5 && ll == -9876543210LL && f == 0.25f, "out got %d %g %lld %g", i, d, ll, (double)f);
    }
}

/* ------------------------------------------------------------------ variadics */
static double lvl(const char *types, va_list ap)
{
    double s = 0;
    for (; *types; types++) {
        switch (*types) {
        case 'i': case 'c': s += va_arg(ap, int); break;
        case 'u': s += (double)va_arg(ap, unsigned); break;
        case 'l': s += (double)va_arg(ap, long long); break;
        case 'd': s += va_arg(ap, double); break;
        case 'p': s += (va_arg(ap, void *) != 0); break;
        default: break;
        }
    }
    return s;
}
static double lva(const char *types, ...)          /* va_list made here, consumed by the callee (abi_vl) */
{
    va_list ap;
    va_start(ap, types);
    double r = abi_vl(types, ap);
    va_end(ap);
    return r;
}
static double lvl_va(const char *types, ...)       /* made and consumed here */
{
    va_list ap;
    va_start(ap, types);
    double r = lvl(types, ap);
    va_end(ap);
    return r;
}
#define VA3(want, ...) do { double w_ = (want); \
        CHECKV(abi_va(__VA_ARGS__) == w_, "abi_va(%s)", #__VA_ARGS__); \
        CHECKV(lva(__VA_ARGS__) == w_, "lva(%s)", #__VA_ARGS__); \
        CHECKV(lvl_va(__VA_ARGS__) == w_, "lvl_va(%s)", #__VA_ARGS__); } while (0)

static void t_varargs(void)
{
    VA3(5.0, "i", 5);
    VA3(2.5, "d", 2.5);
    VA3(7.5, "ld", 3LL, 4.5);
    VA3(6.5, "idl", 1, 2.5, 3LL);
    VA3(10.5, "iidl", 1, 2, 3.5, 4LL);
    VA3(301.25, "lild", 100LL, 1, 200LL, 0.25);
    VA3(55.0, "dddddddddd", 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0);
    VA3(55.0, "iiiiiiiiii", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
    VA3(45.0, "ildildild", 1, 2LL, 3.0, 4, 5LL, 6.0, 7, 8LL, 9.0);
    VA3(97 + 4000000000.0 + 98, "cuc", 'a', 4000000000u, 'b');
    VA3(0.0, "p", (void *)0);
    VA3(1.0, "p", (void *)&g_checks);
    VA3(1.0 + 2 + 3 + 4 + 5 + 6 + 7 + 8, "iiiiiiid", 1, 2, 3, 4, 5, 6, 7, 8.0 - 8.0 + 8.0 - 0.0 + 0.0 - 0.0 + 0.0 - 8.0 + 8.0 - 0.0 + 0.0);
    char buf[160];
    snprintf(buf, sizeof buf, "%d|%lld|%u|%x|%s|%c|%.3f|%5.1f", -42, -5000000000LL, 4000000000u, 0xBEEFu, "str", 'Z', 3.14159, -2.26);
    CHECKV(strcmp(buf, "-42|-5000000000|4000000000|beef|str|Z|3.142| -2.3") == 0, "snprintf gave '%s'", buf);
    volatile double dv = 0.5; volatile long long lv = 1LL << 40;
    snprintf(buf, sizeof buf, "%d %lld %g %d %lld", 1, lv, (double)dv, 2, lv + 1);
    CHECKV(strcmp(buf, "1 1099511627776 0.5 2 1099511627777") == 0, "snprintf gave '%s'", buf);
    volatile double sv = 2500.0;
    CHECK(strtod("2.5e3", NULL) == sv);
    int ai = 0; double ad = 0; char as[8] = "";
    CHECK(sscanf("12 3.5 abc", "%d %lf %7s", &ai, &ad, as) == 3 && ai == 12 && ad == 3.5 && strcmp(as, "abc") == 0);
}

/* ------------------------------------------------------------------ alloca, VLAs, stack layout, unwinding */
static int __attribute__((noinline)) sum_buf(const unsigned char *p, int n)
{
    int s = 0;
    for (int i = 0; i < n; i++) s += p[i] * (i + 1);
    return s;
}
static int ref_sum(int n)
{
    int s = 0;
    for (int i = 0; i < n; i++) s += (unsigned char)(i * 7 + n) * (i + 1);
    return s;
}
static int __attribute__((noinline)) fill_alloca(int n)
{
    unsigned char *p = __builtin_alloca(n + 1);
    for (int i = 0; i < n; i++) p[i] = (unsigned char)(i * 7 + n);
    return sum_buf(p, n);
}
static int __attribute__((noinline)) fill_vla(int n)
{
    unsigned char p[n + 1];
    for (int i = 0; i < n; i++) p[i] = (unsigned char)(i * 7 + n);
    return sum_buf(p, n);
}
static int __attribute__((noinline)) rec_alloca(int depth)
{
    unsigned char *p = __builtin_alloca(16 + depth);
    memset(p, depth, 16 + depth);
    int r = depth ? rec_alloca(depth - 1) : 0;
    for (int i = 0; i < 16 + depth; i++)
        if (p[i] != (unsigned char)depth) return -1000000;
    return r + depth;
}
static int __attribute__((noinline)) rec_sum(int n)
{
    volatile int pad[8];
    pad[0] = n;
    return n == 0 ? 0 : pad[0] + rec_sum(n - 1);
}
static int __attribute__((noinline)) align_probe(int depth)
{
    char a16[24] __attribute__((aligned(16)));
    char a32[40] __attribute__((aligned(32)));
    volatile double d = depth;
    volatile long long ll = depth;
    char *al = __builtin_alloca(depth * 3 + 1);
    int bad = 0;
    bad += ((uintptr_t)a16 & 15) != 0;
    bad += ((uintptr_t)a32 & 31) != 0;
    bad += ((uintptr_t)&d & 7) != 0;
    bad += ((uintptr_t)&ll & 7) != 0;
    bad += ((uintptr_t)al & 7) != 0;
    memset(a16, depth, sizeof a16);
    memset(a32, depth, sizeof a32);
    memset(al, depth, depth * 3 + 1);
    if (depth) bad += align_probe(depth - 1);
    for (unsigned i = 0; i < sizeof a16; i++) bad += a16[i] != (char)depth;
    for (unsigned i = 0; i < sizeof a32; i++) bad += a32[i] != (char)depth;
    for (int i = 0; i < depth * 3 + 1; i++) bad += al[i] != (char)depth;
    return bad;
}

static void t_alloca(void)
{
    for (int n = 0; n <= 300; n++) {
        CHECKV(fill_alloca(n) == ref_sum(n), "alloca n=%d", n);
        CHECKV(fill_vla(n) == ref_sum(n), "vla n=%d", n);
    }
    CHECKV(rec_alloca(24) == 24 * 25 / 2, "rec_alloca");
    CHECKV(rec_sum(1000) == 1000 * 1001 / 2, "rec_sum");
    CHECKV(align_probe(12) == 0, "alignment (16/32-byte locals, alloca, recursion)");
}

#ifndef NO_UNWIND
struct ubt { int n; uintptr_t ip[64]; };
static _Unwind_Reason_Code ubt_cb(struct _Unwind_Context *ctx, void *arg)
{
    struct ubt *u = (struct ubt *)arg;
    if (u->n < 64) u->ip[u->n++] = (uintptr_t)_Unwind_GetIP(ctx);
    return _URC_NO_REASON;
}
static int __attribute__((noinline)) unw3(struct ubt *u)
{
    char *p = __builtin_alloca(40);
    memset(p, 1, 40);
    _Unwind_Backtrace(ubt_cb, u);
    return p[3];
}
static int __attribute__((noinline)) unw2(struct ubt *u)
{
    volatile int v[12];
    v[0] = 5;
    return unw3(u) + v[0];
}
static int __attribute__((noinline)) unw1(struct ubt *u) { return unw2(u) + 1; }

static void t_unwind(void)
{
    struct ubt u;
    memset(&u, 0, sizeof u);
    CHECK(unw1(&u) == 7);
    uintptr_t fn[3] = { (uintptr_t)unw3 & ~(uintptr_t)1, (uintptr_t)unw2 & ~(uintptr_t)1, (uintptr_t)unw1 & ~(uintptr_t)1 };
    int first[3] = { -1, -1, -1 };
    for (int i = 0; i < u.n; i++) {
        int best = -1;
        for (int k = 0; k < 3; k++)
            if (fn[k] < u.ip[i] && u.ip[i] - fn[k] < 1024 && (best < 0 || fn[k] > fn[best])) best = k;
        if (best >= 0 && first[best] < 0) first[best] = i;
    }
#ifdef UNWIND_STRICT
    /* built with -funwind-tables: the unwinder must see our own frames, in order */
    CHECKV(u.n >= 4, "unwinder returned only %d frames", u.n);
    CHECKV(first[0] >= 0 && first[1] > first[0] && first[2] > first[1], "frames not seen in order (unw3=%d unw2=%d unw1=%d)", first[0], first[1], first[2]);
    printf("  (unwind: %d frames, unw3 at #%d, unw2 at #%d, unw1 at #%d)\n", u.n, first[0], first[1], first[2]);
#else
    INFOV(u.n >= 4, "unwinder returned only %d frames", u.n);
    INFOV(first[0] >= 0 && first[1] > first[0] && first[2] > first[1], "frames not seen in order (unw3=%d unw2=%d unw1=%d)", first[0], first[1], first[2]);
#endif
}
#else
static void t_unwind(void) { }
#endif

/* ------------------------------------------------------------------ setjmp / longjmp */
static jmp_buf jb1, jb2;
static int __attribute__((noinline)) deep_jump(int n, int code)
{
    char pad[32];
    memset(pad, n, sizeof pad);
    if (n == 0) longjmp(jb1, code + pad[0]);
    return deep_jump(n - 1, code) + pad[1];
}
static int __attribute__((noinline)) setjmp_body(void)
{
    volatile int local = 7;
    volatile double dl = 1.5;
    int r = setjmp(jb1);
    if (r == 0) {
        local = 8;
        dl = 2.5;
        deep_jump(40, 42);
        return -1;
    }
    return r + local + (int)dl;
}
static void __attribute__((noinline)) opaque_call(void) { __asm__ volatile("" ::: "memory"); }
static void __attribute__((noinline)) clobber_jump(double a, double b, double c, double d)
{
    double t1 = a * b, t2 = c * d, t3 = a + d, t4 = b + c, t5 = a - b, t6 = c - d;
    opaque_call();                                  /* t1..t6 must survive this call: callee-saved VFP regs */
    longjmp(jb2, (int)(t1 + t2 + t3 + t4 + t5 + t6));
}
static int __attribute__((noinline)) setjmp_vfp_inner(void)
{
    int r = setjmp(jb2);
    if (r == 0) clobber_jump(1.5, 2.5, 3.5, 4.5);
    return r;
}
static void t_setjmp(void)
{
    for (int i = 0; i < 50; i++) CHECKV(setjmp_body() == 52, "setjmp_body round %d", i);
    double k1 = opq_d(10.25), k2 = opq_d(20.5), k3 = opq_d(30.75);
    int r = setjmp_vfp_inner();
    CHECKV(r == 29, "longjmp value %d", r);
    INFOV(k1 == 10.25 && k2 == 20.5 && k3 == 30.75, "longjmp does not preserve the VFP callee-saved registers d8-d15 (UnixLib)");
}

/* ------------------------------------------------------------------ unaligned access */
struct __attribute__((packed)) PK { char c0; int i; short s; long long ll; float f; double d; unsigned char tail; };
typedef int __attribute__((aligned(1))) int_a1;
typedef long long __attribute__((aligned(1))) ll_a1;
typedef double __attribute__((aligned(1))) dbl_a1;

static void t_unaligned(void)
{
    static struct PK pk;
    volatile struct PK *p = &pk;
    p->c0 = 'x'; p->i = 0x12345678; p->s = -2; p->ll = 0x0123456789ABCDEFLL; p->f = 1.5f; p->d = -2.25; p->tail = 0xAA;
    CHECK(p->c0 == 'x'); CHECK(p->i == 0x12345678); CHECK(p->s == -2); CHECK(p->ll == 0x0123456789ABCDEFLL);
    CHECK(p->f == 1.5f); CHECK(p->d == -2.25); CHECK(p->tail == 0xAA);
    const unsigned char *b = (const unsigned char *)&pk;
    CHECK(b[1] == 0x78 && b[2] == 0x56 && b[3] == 0x34 && b[4] == 0x12);
    unsigned char raw[24];
    for (int i = 0; i < 24; i++) raw[i] = (unsigned char)(0x10 + i * 3);
    for (int off = 0; off < 8; off++) {
        volatile int o = off;
        uint32_t want32 = raw[off] | (raw[off + 1] << 8) | (raw[off + 2] << 16) | ((uint32_t)raw[off + 3] << 24);
        uint64_t want64 = 0;
        for (int k = 7; k >= 0; k--) want64 = (want64 << 8) | raw[off + k];
        CHECKV((uint32_t)*(int_a1 *)(raw + o) == want32, "unaligned int at +%d", off);
        CHECKV((uint64_t)*(ll_a1 *)(raw + o) == want64, "unaligned long long at +%d", off);
        double dd; memcpy(&dd, raw + o, 8);
        CHECKV(bits_d(dd) == want64, "memcpy double at +%d", off);
        CHECKV(bits_d(*(dbl_a1 *)(raw + o)) == want64, "unaligned double at +%d", off);
        unsigned char w[24] = { 0 };
        *(int_a1 *)(w + o) = (int)0xA1B2C3D4u;
        CHECKV(w[off] == 0xD4 && w[off + 1] == 0xC3 && w[off + 2] == 0xB2 && w[off + 3] == 0xA1, "unaligned int store at +%d", off);
    }
}

/* ------------------------------------------------------------------ atomics */
static void t_atomics(void)
{
    volatile int x = 5;
    int old = __atomic_fetch_add(&x, 3, __ATOMIC_SEQ_CST);
    CHECK(old == 5 && x == 8);
    _Atomic int ax = 10;
    CHECK(atomic_fetch_sub(&ax, 4) == 10 && atomic_load(&ax) == 6);
    int expected = 6;
    CHECK(atomic_compare_exchange_strong(&ax, &expected, 99) && atomic_load(&ax) == 99);
    expected = 1;
    CHECK(!atomic_compare_exchange_strong(&ax, &expected, 7) && expected == 99);
    CHECK(__sync_val_compare_and_swap(&x, 8, 20) == 8 && x == 20);
    CHECK(__sync_fetch_and_or(&x, 3) == 20 && x == 23);
    CHECK(atomic_exchange(&ax, 5) == 99 && atomic_load(&ax) == 5);
    volatile long long ll = 1LL << 40;
    long long o = __atomic_fetch_add(&ll, 5, __ATOMIC_SEQ_CST);
    CHECK(o == (1LL << 40) && ll == (1LL << 40) + 5);
    _Atomic long long a64 = 0;
    atomic_store(&a64, 0x1122334455667788LL);
    CHECK(atomic_load(&a64) == 0x1122334455667788LL);
    CHECK(atomic_fetch_add(&a64, 1) == 0x1122334455667788LL && atomic_load(&a64) == 0x1122334455667789LL);
    atomic_flag fl = ATOMIC_FLAG_INIT;
    CHECK(!atomic_flag_test_and_set(&fl));
    CHECK(atomic_flag_test_and_set(&fl));
    atomic_flag_clear(&fl);
    CHECK(!atomic_flag_test_and_set(&fl));
    __sync_synchronize();
}

/* ------------------------------------------------------------------ misc code generation */
static int __attribute__((noinline)) sw_dense(int x)
{
    switch (x) {
    case 0: return 11;  case 1: return 22;  case 2: return 33;  case 3: return 44;
    case 4: return 55;  case 5: return 66;  case 6: return 77;  case 7: return 88;
    case 8: return 99;  case 9: return 110; case 10: return 121; case 11: return 132;
    case 12: return 143; case 13: return 154; case 14: return 165; case 15: return 176;
    default: return -1;
    }
}
static int __attribute__((noinline)) sw_sparse(int x)
{
    switch (x) {
    case -5: return 1; case 0: return 2; case 100: return 3; case 1000: return 4;
    case 5000: return 5; case 77777: return 6; case 123456789: return 7;
    default: return 0;
    }
}
static int __attribute__((noinline)) cgoto(int i)
{
    static void *const tab[] = { &&L0, &&L1, &&L2, &&L3 };
    int r = 0;
    if (i < 0 || i > 3) return -1;
    goto *tab[i];
L0: r += 1;
L1: r += 10;
L2: r += 100;
L3: r += 1000;
    return r;
}
static int ft_a(int x) { return x + 1; }
static int ft_b(int x) { return x * 2; }
static int ft_c(int x) { return x - 7; }
static int ft_d(int x) { return -x; }
static int (*const ftab[4])(int) = { ft_a, ft_b, ft_c, ft_d };

struct BF { int a : 5; unsigned b : 7; int c : 12; unsigned d : 8; };

static int cmp_int(const void *a, const void *b) { int x = *(const int *)a, y = *(const int *)b; return (x > y) - (x < y); }
struct rec { int key; const char *name; };
static int cmp_rec(const void *a, const void *b) { return strcmp(((const struct rec *)a)->name, ((const struct rec *)b)->name); }

static int fib(int n) { return n < 2 ? n : fib(n - 1) + fib(n - 2); }
static int ack(int m, int n) { return m == 0 ? n + 1 : n == 0 ? ack(m - 1, 1) : ack(m - 1, ack(m, n - 1)); }

static unsigned char cbuf[320], dbuf[320];
#define CONSTCOPY(N) do { \
        for (int so_ = 0; so_ < 4; so_++) for (int dof_ = 0; dof_ < 4; dof_++) { \
            memset(dbuf, 0xA5, sizeof dbuf); \
            memcpy(dbuf + 8 + dof_, cbuf + 8 + so_, N); \
            int ok_ = 1; \
            for (int i_ = 0; i_ < 8 + dof_; i_++) ok_ &= (dbuf[i_] == 0xA5); \
            for (int i_ = 0; i_ < N; i_++) ok_ &= (dbuf[8 + dof_ + i_] == cbuf[8 + so_ + i_]); \
            for (int i_ = 8 + dof_ + N; i_ < 300; i_++) ok_ &= (dbuf[i_] == 0xA5); \
            CHECKV(ok_, "memcpy const %d src+%d dst+%d", N, so_, dof_); \
        } } while (0)
#define STRUCTCOPY(N) do { \
        struct cp##N { char c[N]; }; \
        static struct cp##N s_; struct cp##N d_; \
        for (int i_ = 0; i_ < N; i_++) s_.c[i_] = (char)(i_ * 5 + N); \
        d_ = *(struct cp##N *)opq_ptr(&s_); \
        int ok_ = 1; \
        for (int i_ = 0; i_ < N; i_++) ok_ &= (d_.c[i_] == (char)(i_ * 5 + N)); \
        CHECKV(ok_, "struct copy of %d bytes", N); } while (0)

static void t_misc(void)
{
    for (int x = -3; x <= 20; x++) CHECKV(sw_dense(x) == ((x >= 0 && x <= 15) ? (x + 1) * 11 : -1), "sw_dense(%d)", x);
    static const int sp[][2] = { { -5, 1 }, { 0, 2 }, { 100, 3 }, { 1000, 4 }, { 5000, 5 }, { 77777, 6 }, { 123456789, 7 }, { 1, 0 }, { -6, 0 }, { 99, 0 } };
    for (unsigned i = 0; i < sizeof sp / sizeof sp[0]; i++) CHECKV(sw_sparse(sp[i][0]) == sp[i][1], "sw_sparse(%d)", sp[i][0]);
    CHECK(cgoto(0) == 1111); CHECK(cgoto(1) == 1110); CHECK(cgoto(2) == 1100); CHECK(cgoto(3) == 1000); CHECK(cgoto(4) == -1);
    for (int i = 0; i < 12; i++) {
        int want = (i & 3) == 0 ? i + 1 : (i & 3) == 1 ? i * 2 : (i & 3) == 2 ? i - 7 : -i;
        CHECKV(ftab[i & 3](i) == want, "ftab[%d]", i);
    }

    struct BF bf;
    memset(&bf, 0, sizeof bf);
    volatile int v = -3;
    bf.a = v; bf.b = 100; bf.c = -2000; bf.d = 200;
    CHECK(bf.a == -3 && bf.b == 100 && bf.c == -2000 && bf.d == 200);
    bf.a = 15; bf.c = 2047;
    CHECK(bf.a == 15 && bf.b == 100 && bf.c == 2047 && bf.d == 200);
    bf.a = -16; bf.b = 127; bf.c = -2048; bf.d = 255;
    CHECK(bf.a == -16 && bf.b == 127 && bf.c == -2048 && bf.d == 255);
    CHECK(sizeof(struct BF) == 4);

    int arr[200];
    unsigned s = 12345;
    for (int i = 0; i < 200; i++) { s = s * 1103515245u + 12345u; arr[i] = (int)((s >> 8) % 1000) - 500; }
    int probe = arr[37];
    qsort(arr, 200, sizeof arr[0], cmp_int);
    int sorted = 1;
    for (int i = 1; i < 200; i++) sorted &= arr[i - 1] <= arr[i];
    CHECK(sorted);
    int *f = bsearch(&probe, arr, 200, sizeof arr[0], cmp_int);
    CHECK(f != NULL && *f == probe);
    int missing = 100000;
    CHECK(bsearch(&missing, arr, 200, sizeof arr[0], cmp_int) == NULL);
    struct rec recs[5] = { { 1, "pear" }, { 2, "apple" }, { 3, "fig" }, { 4, "zebra" }, { 5, "mango" } };
    qsort(recs, 5, sizeof recs[0], cmp_rec);
    CHECK(!strcmp(recs[0].name, "apple") && !strcmp(recs[1].name, "fig") && !strcmp(recs[2].name, "mango") && !strcmp(recs[3].name, "pear") && !strcmp(recs[4].name, "zebra"));
    CHECK(recs[0].key == 2 && recs[4].key == 4);

    const char *hs = "hello, world";
    CHECK(strlen(hs) == 12); CHECK(strcmp(hs, "hello, world") == 0); CHECK(strcmp("abc", "abd") < 0);
    CHECK(strchr(hs, 'w') == hs + 7); CHECK(memcmp("abc", "abd", 3) < 0); CHECK(strncmp("abcdef", "abcxyz", 3) == 0);
    char sb[32];
    strcpy(sb, "ab"); strcat(sb, "cd");
    CHECK(strcmp(sb, "abcd") == 0);
    strncpy(sb, "xy", 5);
    CHECK(sb[0] == 'x' && sb[1] == 'y' && sb[2] == 0 && sb[4] == 0);
    CHECK(atoi("-123") == -123); CHECK(strtol("7fffffff", NULL, 16) == 0x7fffffff);

    CHECK(fib(22) == 17711); CHECK(ack(2, 3) == 9);
    volatile unsigned char uc = 200; volatile signed char sc = (signed char)200; volatile short sh = (short)40000; volatile unsigned short us = 65535;
    CHECK((unsigned char)(uc + 100) == 44); CHECK(sc == -56); CHECK(sh == -25536); CHECK((unsigned short)(us + 2) == 1);
    CHECK((int)(unsigned char)-1 == 255); CHECK((unsigned)(int)-1 == 0xFFFFFFFFu);

    for (int i = 0; i < 320; i++) cbuf[i] = (unsigned char)(i * 13 + 1);
    CONSTCOPY(1); CONSTCOPY(2); CONSTCOPY(3); CONSTCOPY(4); CONSTCOPY(5); CONSTCOPY(6); CONSTCOPY(7); CONSTCOPY(8);
    CONSTCOPY(9); CONSTCOPY(11); CONSTCOPY(12); CONSTCOPY(13); CONSTCOPY(15); CONSTCOPY(16); CONSTCOPY(17);
    CONSTCOPY(23); CONSTCOPY(24); CONSTCOPY(31); CONSTCOPY(32); CONSTCOPY(33); CONSTCOPY(48); CONSTCOPY(64); CONSTCOPY(65);
    CONSTCOPY(100); CONSTCOPY(130); CONSTCOPY(257);
    STRUCTCOPY(1); STRUCTCOPY(2); STRUCTCOPY(3); STRUCTCOPY(4); STRUCTCOPY(5); STRUCTCOPY(7); STRUCTCOPY(8); STRUCTCOPY(9);
    STRUCTCOPY(12); STRUCTCOPY(15); STRUCTCOPY(16); STRUCTCOPY(17); STRUCTCOPY(24); STRUCTCOPY(31); STRUCTCOPY(32);
    STRUCTCOPY(33); STRUCTCOPY(48); STRUCTCOPY(64); STRUCTCOPY(100);
    for (int n = 0; n <= 70; n++) for (int so = 0; so < 4; so++) for (int dof = 0; dof < 4; dof++) {
        volatile int nn = n;
        memset(dbuf, 0xA5, sizeof dbuf);
        memcpy(dbuf + 8 + dof, cbuf + 8 + so, nn);
        int ok = 1;
        for (int i = 0; i < n; i++) ok &= (dbuf[8 + dof + i] == cbuf[8 + so + i]);
        ok &= (dbuf[7 + dof] == 0xA5) && (dbuf[8 + dof + n] == 0xA5);
        CHECKV(ok, "memcpy n=%d src+%d dst+%d", n, so, dof);
    }
    memcpy(dbuf, cbuf, 64);
    memmove(dbuf + 3, dbuf, 40);
    int mv = 1;
    for (int i = 0; i < 40; i++) mv &= (dbuf[3 + i] == cbuf[i]);
    CHECK(mv);
}

/* ------------------------------------------------------------------ position-independent data (picdata.c: in the exe or in libfoo.so) */
static int cb_inc(int x) { return x + 1000; }

static void t_picdata(void)
{
    CHECK(pd_sum_list() == 6);
    CHECK(pd_via_ptr() == 10);
    CHECK(strcmp(pd_name(0), "alpha") == 0 && strcmp(pd_name(1), "beta") == 0 && strcmp(pd_name(5), "gamma") == 0);
    int c0 = pd_counter;
    CHECK(pd_call(0, 10) == 11); CHECK(pd_call(1, 10) == 20); CHECK(pd_call(2, 10) == 7);
    CHECK(pd_counter == c0 + 3);
    CHECK(pd_read_ext() == 42);
    pd_ext = 100;
    CHECK(pd_read_ext() == 101);
    pd_ext = 41;
    CHECK(pd_apply(cb_inc, 5) == 1005 + pd_counter);
    CHECK(pd_cptr_sum() == 60);
    for (int i = -2; i < 14; i++) CHECKV(pd_switch(i) == ((i >= 0 && i <= 11) ? 100 + i * 111 : -1), "pd_switch(%d)", i);
    CHECK(pd_static_count() == 41); CHECK(pd_static_count() == 42);
    CHECK(pd_funcs[1](21) == 42); CHECK(strcmp(pd_names[2], "gamma") == 0); CHECK(pd_head->next->next->v == 3); CHECK(*pd_ptr == 5);
    CHECK(*pd_cptrs[1] == 40);
}

#ifdef WITH_DLOPEN
static void t_dlopen(void)
{
    void *h = dlopen(FOO_SONAME, RTLD_NOW);
    INFOV(h != NULL, "dlopen(%s) failed: %s", FOO_SONAME, dlerror());
    if (h) {
        int (*fn)(int, int) = (int (*)(int, int))dlsym(h, "pd_call");
        CHECK(fn != NULL);
        if (fn) CHECK(fn(0, 10) == 11);
        INFOV(dlsym(h, "pd_call") == (void *)pd_call, "dlopen gave a different instance than the linked library");
        dlclose(h);
    }
}
#endif

#ifdef HAVE_C23
extern int c23_probe(int);
static void t_c23(void)
{
    CHECK(c23_probe(2) == 15);
    CHECK(c23_probe(1) == -8);
}
#endif

static void t_jit(void)
{
#ifdef __arm__
    uint32_t *code = malloc(64);
    code[0] = 0xE3A0002Au;                      /* mov r0, #42 */
    code[1] = 0xE12FFF1Eu;                      /* bx lr */
    __builtin___clear_cache((char *)code, (char *)(code + 2));
    int (*fn)(void) = (int (*)(void))(uintptr_t)code;
    CHECKV(fn() == 42, "generated code returned the wrong value");
    free(code);
#else
    puts("  (jit test only exists for ARM)");
#endif
}

#define RUN(fn) do { int c0_ = g_checks, f0_ = g_fail; g_gf = 0; g_grp = #fn + 2; fn(); \
        printf("  %-10s %6d checks  %s\n", #fn + 2, g_checks - c0_, g_fail == f0_ ? "ok" : "FAILED"); } while (0)

int main(int argc, char **argv)
{
    int jit = argc > 1 && !strcmp(argv[1], "jit");
    printf("rotest 1.0 [%s] gcc %s\n", ROTEST_CFG, __VERSION__);
    RUN(t_int32); RUN(t_int64); RUN(t_f64); RUN(t_f32); RUN(t_conv); RUN(t_fpmisc); RUN(t_complex);
    RUN(t_abi); RUN(t_varargs); RUN(t_alloca); RUN(t_unwind); RUN(t_setjmp); RUN(t_unaligned); RUN(t_atomics);
    RUN(t_misc); RUN(t_picdata);
#ifdef WITH_DLOPEN
    RUN(t_dlopen);
#endif
#ifdef HAVE_C23
    RUN(t_c23);
#endif
    if (jit) RUN(t_jit);
    printf("INFO: %d informational checks, %d differ\n", g_info, g_info_fail);
    printf("SUMMARY [%s]: %d checks, %d failed -> %s\n", ROTEST_CFG, g_checks, g_fail, g_fail ? "FAIL" : "PASS");
    return g_fail ? 1 : 0;
}
