#!/usr/bin/env python3
"""mkrename.py OUTDIR [INCLUDE_DIR] - writes OUTDIR/mk_rename.h and OUTDIR/mk_decl.h for the host build of the library tests.

The library of modkit has the names of the C library (strlen, strtol, sscanf ...).  For the test on the host the library is compiled with every one of those names prefixed mk_ (mk_rename.h, included
first), and the test program, which includes the host's headers, includes mk_rename.h after them and mk_decl.h (the prototypes of the mk_ functions, made from the extern lines of modkit's headers),
so that its calls of strlen, strtol ... go to the library and the program can still be built against glibc itself, without the two files."""
import os, re, sys

out = sys.argv[1]
inc = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "include")
EXCLUDE = set("malloc free calloc realloc printf vprintf puts putchar exit _Exit abort atexit getenv setjmp longjmp".split())
CTYPE = "isalnum isalpha iscntrl isdigit isgraph islower isprint ispunct isspace isupper isxdigit isblank isascii toascii tolower toupper".split()
names, protos = [], []
for h in ("string.h", "stdlib.h", "stdio.h", "time.h", "locale.h"):
    for line in open(os.path.join(inc, h)):
        m = re.match(r"^extern\s+([^()]*?)\b(\w+)\s*\((.*)$", line.rstrip("\n"))
        if not m or m.group(2) in EXCLUDE or m.group(2).startswith("__modlib"):
            continue
        name = m.group(2)
        names.append(name)
        protos.append("extern %s mk_%s (%s" % (m.group(1), name, m.group(3)))
for c in CTYPE:
    names.append(c); protos.append("extern int mk_%s (int);" % c)
os.makedirs(out, exist_ok=True)
with open(os.path.join(out, "mk_rename.h"), "w") as f:
    f.write("/* generated by mkrename.py: the library's C functions are called mk_NAME in the host build of the tests */\n")
    for n in names:
        f.write("#undef %s\n#define %s mk_%s\n" % (n, n, n))
with open(os.path.join(out, "mk_decl.h"), "w") as f:
    f.write("/* generated by mkrename.py: the prototypes of the mk_ functions */\n")
    f.write("\n".join(protos) + "\n")
print("%d names" % len(names))
