# CxxMod: a module written in C++ (see cxxmod.cc).  Needs the kit after 16.2.0-16 (lib/cxxrt.c, the extern "C" headers) and  make  with module.mk:   make BIN=<tool chain>/bin
MODULE = CxxMod
CMHG   = cxxmod.cmhg
SRCS   = cxxmod.cc
include ../../module.mk
