#!/usr/bin/env python3
"""gen.py -- write swi-wrapper-test.c: for every inline SWI wrapper of UnixLib's incl-local/internal/os.h a test function that calls the OLD (pristine) and the NEW (fixed) version with
the same arguments (struct tc: in[] = the arguments, out[] = the output variables, ret = the returned error).  usage: gen.py OLD_OS_H NEW_OS_H OUTDIR"""
import re, sys

OLD, NEW, OUT = sys.argv[1:4]
# name: parameter kinds in order: i = integer from in[k], p = pointer from in[k], o = the address of out[k] (an output variable the wrapper stores through)
SPEC = [
 ("SWI_OS_Byte", "iiioo"), ("SWI_OS_CLI", "p"), ("SWI_OS_Find_Open", "ipo"), ("SWI_OS_Find_Close", "i"),
 ("SWI_OS_File_SaveBlockLoadExec", "piiii"), ("SWI_OS_File_WriteCatLoadExecAttr", "piii"), ("SWI_OS_File_WriteCatInfoAttr", "pi"),
 ("SWI_OS_File_DeleteObject", "p"), ("SWI_OS_File_CreateDirectory", "p"), ("SWI_OS_File_CreateFileWithFileType", "pii"),
 ("SWI_OS_File_ReadCatInfo", "poooooo"[:6]), ("SWI_OS_File_WriteCatInfoFileType", "pi"),
 ("SWI_OS_GBPB_ReadBytes", "ipio"), ("SWI_OS_GBPB_WriteBytes", "ipio"), ("SWI_OS_ChangeRedirection", "iioo"),
 ("SWI_DDEUtils_SetCLSize", "i"), ("SWI_DDEUtils_SetCL", "p"), ("SWI_DDEUtils_GetCLSize", "o"), ("SWI_DDEUtils_GetCL", "p"),
 ("SWI_DDEUtils_Prefix", "p"), ("SWI_DDEUtils_ReadPrefix", "io"),
 ("SWI_OS_FSControl_Rename", "pp"), ("SWI_OS_FSControl_SetCurDir", "p"), ("SWI_OS_FSControl_Canonicalise", "pppio"),
 ("SWI_OS_Args_GetFilePtr", "io"), ("SWI_OS_Args_SetFilePtr", "ii"), ("SWI_OS_Args_GetExtent", "io"), ("SWI_OS_Args_SetExtent", "ii"),
 ("SWI_OS_Args_Canonicalise", "ipio"), ("SWI_OS_Args_GetFileHandleStatus", "io"), ("SWI_OS_Args_Flush", "i"),
 ("SWI_Territory_ConvertTimeToOrdinals", "ipp"),
]
# the real parameter lists (the order in the header); ReadCatInfo has 5 output pointers: objtype loadaddr execaddr objlen attr
SPEC = [(n, k) if n != "SWI_OS_File_ReadCatInfo" else (n, "pooooo") for n, k in SPEC]
# the output pointer arguments of OS_Byte are int *, of ReadCatInfo unsigned *, and so on: the cast is by the compiler from void *; write (void *) casts everywhere
def call(prefix, name, kinds):
    args, ii, oo = [], 0, 0
    for k in kinds:
        if k == "i": args.append("(int) t->in[%d]" % ii); ii += 1
        elif k == "p": args.append("(void *) t->in[%d]" % ii); ii += 1
        else: args.append("(void *) &t->out[%d]" % oo); oo += 1
    return "%s%s (%s)" % (prefix, name, ", ".join(args))

def mk(path, prefix, guard):
    s = open(path).read()
    s = s.replace("__INTERNAL_OS_H", guard)
    s = re.sub(r"\bSWI_", prefix + "SWI_", s)
    for extra in ("armeabisupport_cleanup", "som_deregister_client"):
        s = re.sub(r"\b" + extra + r"\b", prefix.lower() + extra, s)
    return s

open(OUT + "/os_old.h", "w").write(mk(OLD, "OLD_", "__OLD_OS_H"))
open(OUT + "/os_new.h", "w").write(mk(NEW, "NEW_", "__NEW_OS_H"))
c = ['/* generated by gen.py */', '#include <stddef.h>', '#include "os_old.h"', '#include "os_new.h"', 'struct tc { unsigned in[8]; unsigned out[8]; unsigned ret; };',
     'int __get_feature_imagefs_is_file (void) { return 1; }']
tests = []
for name, kinds in SPEC:
    for pre in ("OLD_", "NEW_"):
        fn = "t_%s%s" % (pre, name[4:])
        c.append("void %s (struct tc *t) { t->ret = (unsigned) %s; }" % (fn, call(pre, name, kinds)))
    tests.append(name[4:])
open(OUT + "/swi-wrapper-test.c", "w").write("\n".join(c) + "\n")
open(OUT + "/tests.txt", "w").write("\n".join(tests) + "\n")
print("wrote %d test pairs" % len(tests))
