#!/usr/bin/env python3
"""Make the UnixLib patches of the upstream reports against PRISTINE upstream (svn trunk r7800, the files of a clean working copy ~/gccsdk/gcc4/recipe/files/gcc/libunixlib):
   unixlib-vfork-child-pthread-fini.patch    pthread/pthinit.c: __pthread_prog_fini returns while the program image is shared (a vfork child that ends without exec)
   unixlib-free-signal-stack.patch           EABI: give the signal stack back at exit / exec (unix.h, unix/unix.c, sys/exec.c, vscript)
   unixlib-mmap-refuse-impossible.patch      EABI: mmap / mremap refuse a request that can never be served before ARMEABISupport makes an area for it (sys/mman-armeabi.c)
   unixlib-vfork-exec-heap-limit.patch       appspace_himem is never raised above the permitted RAM limit the program was started with: the heap of a vfork + exec child cannot grow over the copy of its parent
 and the ten smaller ones of the second batch of reports (09 - 18): stdio-short-transfers, pthread-once, pthread-cond-timedwait, sleep-threads, sysconf-nprocessors, gcc14-implicit-declarations,
   touch-stack-buffers, memcpy-split-vstm, eabi-stack-size, da-heap-fallback;
 and the two of the third batch (reports 19, 20): inline-swi-register-variables (incl-local/internal/os.h, generated by tools/fix-unixlib-regvars.py), ddeutils-prefix-loop (common/prefix.c);
 and the one of the fourth batch (report 21): scanf-long-long (stdio/scanf.c);
 and the three of the fifth batch (reports 22 - 24): fini-array (stdlib/atexit.c, sys/_syslib.s, vscript), getrlimit-stack (sys/_syslib.s, vscript, resource/initialise.c),
   semaphores (pthread/sem.c and the declaration of sem_timedwait in include/semaphore.h: two patches of the recipe in one).
They start from the patches of the GCCSDK GCC 16 forward-port (recipe patches-unixlib), applied to the pristine files; the comments are made upstream-neutral.  No ChangeLog hunk (a suggested entry is in each report).
usage: make-upstream-unixlib-patches.py OUTDIR [PATCHNAME ...]"""
import os, shutil, subprocess, sys, tempfile
UPS = os.path.expanduser("~/gccsdk/gcc4/recipe/files/gcc/libunixlib")
PAT = os.path.expanduser("~/gccsdk-next/recipe/gcc-16.2.0-riscos/patches-unixlib")
PREFIX = "gcc4/recipe/files/gcc/libunixlib/"
JOBS = {
  "unixlib-vfork-child-pthread-fini.patch": ("unixlib-vfork-child-pthread-fini.patch", ["pthread/pthinit.c"]),
  "unixlib-free-signal-stack.patch": ("unixlib-eabi-free-signal-stack.patch", ["incl-local/internal/unix.h", "unix/unix.c", "sys/exec.c", "vscript"]),
  "unixlib-mmap-refuse-impossible.patch": ("unixlib-eabi-mmap-limit.patch", ["sys/mman-armeabi.c"]),
  "unixlib-vfork-exec-heap-limit.patch": ("unixlib-vfork-exec-heap-limit.patch", ["incl-local/internal/unix.h", "incl-local/internal/asm_dec.s", "sys/_syslib.s", "sys/stackalloc.c"]),
  # second batch (reports 09 - 18)
  "unixlib-stdio-short-transfers.patch": ("unixlib-stdio-short-transfers.patch", ["stdio/fread.c", "stdio/fwrite.c"]),
  "unixlib-pthread-once.patch": ("unixlib-pthread-once.patch", ["pthread/once.c"]),
  "unixlib-pthread-cond-timedwait.patch": ("unixlib-pthread-cond-timedwait.patch", ["pthread/cond.c"]),
  "unixlib-sleep-threads.patch": ("unixlib-sleep-threads.patch", ["signal/sleep.c"]),
  "unixlib-sysconf-nprocessors.patch": ("unixlib-sysconf-nprocessors.patch", ["include/unistd.h"]),
  "unixlib-gcc14-implicit-declarations.patch": ("unixlib-gcc14-implicit-declarations.patch", ["unix/stat.c", "unix/lstat.c", "unix/ul_close.c", "string/strndup.c", "stdlib/msort.c"]),
  "unixlib-touch-stack-buffers.patch": ("unixlib-touch-stack-buffers.patch", ["incl-local/internal/unix.h", "unix/dev.c", "netlib/recv.c", "netlib/recvfrom.c"]),
  "unixlib-memcpy-split-vstm.patch": ("unixlib-memcpy-split-vstm.patch", ["string/_memcpymove-v7l.s"]),
  "unixlib-eabi-stack-size.patch": ("unixlib-eabi-stack-size.patch", ["sys/_syslib.s"]),
  "unixlib-da-heap-fallback.patch": ("unixlib-da-heap-fallback.patch", ["sys/_syslib.s"]),
  # third batch (reports 19, 20)
  "unixlib-inline-swi-register-variables.patch": ("unixlib-inline-swi-register-variables.patch", ["incl-local/internal/os.h"]),
  "unixlib-ddeutils-prefix-loop.patch": ("unixlib-ddeutils-prefix-loop.patch", ["common/prefix.c"]),
  # fourth batch (report 21)
  "unixlib-scanf-long-long.patch": ("unixlib-scanf-long-long.patch", ["stdio/scanf.c"]),
  # fifth batch (reports 22 - 24)
  "unixlib-fini-array.patch": ("unixlib-fini-array.patch", ["stdlib/atexit.c", "sys/_syslib.s", "vscript"]),
  "unixlib-getrlimit-stack.patch": ("unixlib-getrlimit-stack.patch", ["sys/_syslib.s", "vscript", "resource/initialise.c"]),
  "unixlib-semaphores.patch": (("unixlib-sem-blocking-timedwait.patch", "unixlib-semaphore-timedwait-decl.patch"), ["pthread/sem.c", "include/semaphore.h"]),
}
# comment clean-up (old -> new), applied to the patched files
EDITS = {
  "unix/unix.c": [("/* GCCSDK GCC 16 forward-port: give back the signal stack.  _syslib.s", "/* Give back the signal stack.  _syslib.s")],
  "sys/mman-armeabi.c": [("/* GCCSDK GCC 16 forward-port: a request that can never be served is refused here", "/* A request that can never be served is refused here")],
  "pthread/pthinit.c": "BLOCK",
}
REGVAR_COMMENT = """/* The inline SWI wrappers.

   GCC guarantees a local register variable (register T x __asm ("r1")) to be
   in its register only where it is an operand of an asm statement; anywhere
   else the variable IS the hard register, and a call between the asm and the
   use of the variable has overwritten it.  So the registers of a SWI are
   passed in as operands, and the results are copied out INSIDE the asm
   (MOV %[out], rN at the end of the template, early clobber) into ordinary
   variables.  A register that the SWI changes and that is not an operand is
   a clobber; an input whose register the SWI changes is an in-out operand.
   A result that is read in C after the asm is not safe: GCC 16 at -O2 made
   __unixinit use the result of strlen () for the size of the DDEUtils
   command line.  */

"""
JOB_EDITS = {
  "unixlib-inline-swi-register-variables.patch": {"incl-local/internal/os.h": [
    ("static __inline__ const _kernel_oserror * __attribute__ ((always_inline))\nSWI_OS_Byte (", REGVAR_COMMENT + "static __inline__ const _kernel_oserror * __attribute__ ((always_inline))\nSWI_OS_Byte (")]},
  "unixlib-eabi-stack-size.patch": {"sys/_syslib.s": [
    ("unless the program defines __stack_size (in bytes) and asks for more (GCCSDK GCC 16 forward-port; before,\n\t@ the stack of an EABI program was always 1MB).",
     "unless the program defines __stack_size (in bytes) and asks for more (before,\n\t@ the stack of an EABI program was always 1MB).")]},
  "unixlib-da-heap-fallback.patch": {"sys/_syslib.s": [
    ("Try half of the size, and so on down to 2MB, instead (GCCSDK GCC 16 forward-port): the biggest size that fits",
     "Try half of the size, and so on down to 2MB, instead: the biggest size that fits")]},
  "unixlib-memcpy-split-vstm.patch": {"string/_memcpymove-v7l.s": [
    ("/* GCCSDK GCC 16 forward-port: no 64-byte store-multiple.  On the Cortex-A72 machine this was developed on, a vstm of 8 d registers",
     "/* No 64-byte store-multiple.  On a Cortex-A72 machine running RISC OS 5.30, a vstm of 8 d registers")]},
}
PTHREAD_COMMENT = """/* Called once, at program finalisation, by the last user of the program image.

   Not by a vfork child that ends without exec.  Such a child (the usual reaction to an exec that failed: vfork (); if (child) { execv (...); _exit (127); })
   shares the program image with its parent - this RMA block, __ul_global and the pthread system included - and its _exit () used to free the block here, under the parent's feet: the
   parent went on with a pointer to freed RMA memory (setjmp/longjmp, the signal code and every PTHREAD_UNSAFE section write into the block) and freed it a second time when it ended.
   With one such child the block was still free when the parent freed it again and nothing showed; if the RMA hands the block out in between, the parent goes on using, and then
   frees, memory that belongs to somebody else.  __dynamic_area_refcount is the number of processes that share the image: the vfork child has added itself in __fork_post () and
   takes itself off in __dynamic_area_exit (), which _exit () calls AFTER this function, so more than one means that the image is not this process's to take down; the last user
   (the parent, when it ends) frees the block, once.  */"""
def main():
    out = sys.argv[1]; os.makedirs(os.path.join(out, "patches"), exist_ok=True)
    only = sys.argv[2:]                       # optional: only these patch names (the others are left as they are in OUTDIR)
    for name, (recipe, files) in JOBS.items():
        if only and name not in only: continue
        w = tempfile.mkdtemp(prefix="ulpatch-")
        a, b = os.path.join(w, "a"), os.path.join(w, "b")
        for root in (a, b):
            for f in files:
                os.makedirs(os.path.join(root, "libunixlib", os.path.dirname(f)), exist_ok=True); shutil.copy(os.path.join(UPS, f), os.path.join(root, "libunixlib", f))
        for rp in ((recipe,) if isinstance(recipe, str) else recipe):
            r = subprocess.run(["patch", "-p1", "-s", "--no-backup-if-mismatch", "-i", os.path.join(PAT, rp)], cwd=b, capture_output=True, text=True)
            assert r.returncode == 0, r.stdout + r.stderr
        for f in files:
            p = os.path.join(b, "libunixlib", f); t = open(p).read()
            if name in JOB_EDITS and f in JOB_EDITS[name]:
                for old, new in JOB_EDITS[name][f]:
                    assert t.count(old) == 1, (name, f, old[:50]); t = t.replace(old, new)
            elif EDITS.get(f) == "BLOCK" and name == "unixlib-vfork-child-pthread-fini.patch":
                a0 = t.index("/* Called once, at program finalisation, by the last user of the program image."); a1 = t.index("*/", a0) + 2
                t = t[:a0] + PTHREAD_COMMENT + t[a1:]
            else:
                edits = EDITS.get(f, [])
                for old, new in ([] if edits == "BLOCK" else edits):
                    assert t.count(old) == 1, (f, old[:50]); t = t.replace(old, new)
            assert "forward-port" not in t.replace("GCCSDK GCC 16 forward-port", "FWDPORT") or "FWDPORT" not in t or True
            open(p, "w").write(t)
        diff = ""
        for f in files:
            d = subprocess.run(["diff", "-u", "--label", "a/" + PREFIX + f, "--label", "b/" + PREFIX + f, os.path.join(a, "libunixlib", f), os.path.join(b, "libunixlib", f)], capture_output=True, text=True)
            assert d.returncode in (0, 1)
            diff += d.stdout
        assert "forward-port" not in diff, "a forward-port remark is left in " + name
        open(os.path.join(out, "patches", name), "w").write(diff)
        os.makedirs(os.path.join(out, "src", name[:-6]), exist_ok=True)
        for f in files:
            dst = os.path.join(out, "src", name[:-6], f); os.makedirs(os.path.dirname(dst), exist_ok=True); shutil.copy(os.path.join(b, "libunixlib", f), dst)
        print("%-42s %3d lines" % (name, diff.count("\n"))); shutil.rmtree(w)
main()
